### ISSUE TITLE
Help,Why do I report errors when I run 'python run.py' directly???

### ISSUE THREAD

**Issue by waifungloo** [owenzlz/Deep_Image_Blending#6]
I didn't make any changes,but it made a mistake.

Traceback (most recent call last):
  File "run.py", line 219, in <module>
    optimizer.step(closure)
  File "/home/ubuntu/anaconda3/envs/lwf/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/lwf/lib/python3.6/site-packages/torch/optim/lbfgs.py", line 316, in step
    flat_grad = self._gather_flat_grad()
  File "/home/ubuntu/anaconda3/envs/lwf/lib/python3.6/site-packages/torch/optim/lbfgs.py", line 255, in _gather_flat_grad
    view = p.grad.view(-1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by Akbarmq01** [comment]
Got the same error. Has anyone resolved it?

**Comment by saandeepa93** [comment]
Download the optimizer source code of LBFGS as a separate python file in your local code from [pytorch github](https://github.com/pytorch/pytorch/blob/0743d013a6d9283b82adac847622294b229a3b0b/torch/optim/lbfgs.py#L183)  instead of importing it as "nn.optim.LBFGS ". Also, import the libraries for this file as
`import torch`
`from functools import reduce`
`from torch.optim import Optimizer` 

1. In new class file, change the line _view = p.grad.view(-1)_ to **_view = p.grad.contiguous().view(-1)_** .
2. Also make sure to instantiate the optimizer class of your local code rather than nn.optim in _run.py_. 

Re-run your code and it should work.

**Comment by amil-rp-work** [comment]
@saandeepa93  Your solution works perfectly!
I have trouble while understanding the argument `--x` & `--y` in the `run.py` file. I believe they help me decide the starting point from which the mask needs to be placed (assuming origin is top left corner). 
I am observing these coordinates to go below 0 or more than the image shape? why is that so?

Also please provide some ideas to improve the output, I have observed the second stage output to be worse than first stage?

**Comment by ManuLasker** [comment]
Just change line 63 in `run.py`

from: 
```
input_img = torch.randn(target_img.shape).to(gpu_id)
```
to:
```
input_img = torch.randn(target_img.shape).contiguous().to(gpu_id)
```
this solution works for me :)

**Comment by sanspareilsmyn** [comment]
You can just directly change lbfgs.py installed in your site-packages folder.
In my case, I've changed one line of lbfgs.py in '..Python\Python37\Lib\site-packages\torch\optim'.

from:
```
view = p.grad.view(-1)
```

to:
```
view = p.grad.contiguous().view(-1)
```
